### ISSUE TITLE
Terms and Conditions for refund or return policies 

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#12]

**Comment by avoxaya** [comment]
Please assign me this issue under OSoC'23

**Comment by prathamkandari** [comment]
Sure

**Comment by chshiv** [comment]
please allow me to work on this issue

**Comment by prathamkandari** [comment]
okay you too can. The one who finished first with the most accuracy will get the points.

**Comment by shradiphylleia** [comment]
if not currently work in progress, then I would like work on the issue.

**Comment by prathamkandari** [comment]
I have assigned it but I'll assign it to you as well

**Comment by shradiphylleia** [comment]
I have opened a PR please provide suggestions if any changes required.thx!

**Comment by prathamkandari** [comment]
Looks Good!
