### ISSUE TITLE
Implementation of the ChatBot  

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#15]

**Comment by avnigoyal25** [comment]
Hey I can work on this issue.

**Comment by prathamkandari** [comment]
Yeah sure Avni

**Comment by avnigoyal25** [comment]
hey kindly tell me what are the things to be included in the chatbot?

**Comment by prathamkandari** [comment]
Just see if you can build a chatbot like if you ask any question it'll be able to answer that or if not this then we can build something like we can feed a certain amount of questions and then if any question from the user matches it'll be be able to answer that.

**Comment by avnigoyal25** [comment]
can we discuss this on discord?

**Comment by prathamkandari** [comment]
Yeah sure. You can join the vc at 6PM today

**Comment by prathamkandari** [comment]
Completed!
