### ISSUE TITLE
Improve the readme.md

### ISSUE THREAD

**Issue by karthiknadar1204** [upes-open/OSoC-Swayam-Bazaar#17]
Here i propose to make the readme elaborate by adding an elaborate way to open a pr and set up the project as well as shell commands so that anyone starting out with the project can start out easily

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by prathamkandari** [comment]
Okay Karthik I'll assign this to you

**Comment by prathamkandari** [comment]
Hello there
Updating the README.md is not a feature solving in the project.

the readme is already designed by our heads, also the documentation will be done at the last of the OSoC'23.

Updating the README.md will contain the UI screenshots, brief features of project.

**Comment by karthiknadar1204** [comment]
So no points for the readme?

**Comment by prathamkandari** [comment]
Nope

**Comment by harshitgautam2003** [comment]
i would like to do it @prathamkandari
