### ISSUE TITLE
Improve the UI for the Feed page 

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#23]

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by prathamkandari** [comment]
Go ahead

**Comment by prathamkandari** [comment]
Completed!

**Comment by ThapaVinay** [comment]
is this issue not complete?
what more change you want in the ui

**Comment by prathamkandari** [comment]
@ThapaVinay there are 2 pages one is the feedback page and one is the feed page. I think right now you have done only for the feedback one

**Comment by prathamkandari** [comment]
For the feed page you need to connect it to the database. DM me on discord I'll provide you the id and pass to login in mongo compass

**Comment by prathamkandari** [comment]
Completed!
