### ISSUE TITLE
SignIn and SignUp page connected with the database in MongoDB

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#3]

**Comment by ap766** [comment]
Hi! Could i work on this ? Also should I also be creating the frontend of the signup and signin? And should I also implement jwt authentication?

**Comment by prathamkandari** [comment]
Okay I'll assign this to you

**Comment by prathamkandari** [comment]
@ap766 hey are you working on this issue ??

**Comment by ap766** [comment]
yes @prathamkandari  will be done by today.

**Comment by ap766** [comment]
really apologize for the delay!

**Comment by ap766** [comment]
I am sorry for the delay

**Comment by prathamkandari** [comment]
Are you working on the UI part of signin and signup as well?

**Comment by prathamkandari** [comment]
Right now I would suggest just connect it to the backend

**Comment by ap766** [comment]
Yes will do that

**Comment by prathamkandari** [comment]
Ohkay cool
