### ISSUE TITLE
Designing a logo for Swayam Bazaar Application

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#35]

**Comment by Charu-2718** [comment]
Can I work on this issue?

**Comment by prathamkandari** [comment]
Done

**Comment by priii-25** [comment]
I want to work on this issue

**Comment by Charu-2718** [comment]
![Logo](https://github.com/upes-open/OSoC-Swayam-Bazaar/assets/106206014/eaa44bf3-985d-4fbf-b61e-62ac239beb1f)

**Comment by prathamkandari** [comment]
Completed !
