### ISSUE TITLE
Responsive Navbar with theme switch 

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#4]
Theme switch = Dark and Light mode

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by prathamkandari** [comment]
Okay

**Comment by priii-25** [comment]
I would like to work on this issue!

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by ThapaVinay** [comment]
i want to work on this? and can you tell me the content of navbar what all routes will be there

**Comment by prathamkandari** [comment]
@ThapaVinay @priii-25 For now we will have Home, About, Contact Us, Feedbacks. Theme switch should be available for every page.

**Comment by prathamkandari** [comment]
@ThapaVinay the page should be responsive  along with the navbar

**Comment by prathamkandari** [comment]
Issue Completed !
