### ISSUE TITLE
Signin and Signup page responsiveness

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#5]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by prathamkandari** [comment]
Done

**Comment by karthiknadar1204** [comment]
@prathamkandari The project doesn't seem to have been initialized, should I initialize it or is there already an issue for it

**Comment by prathamkandari** [comment]
I've added the boiler plate. You can refer to that

**Comment by GaganChaudhary6378** [comment]
Hi , I want to work on this issue . Can you assign it to me?

**Comment by prathamkandari** [comment]
@GaganChaudhary6378 sure
