### ISSUE TITLE
Feature for adding more similar items to the cart

### ISSUE THREAD

**Issue by prathamkandari** [upes-open/OSoC-Swayam-Bazaar#7]
Adding the feature on the right side of every product like +1,+2, (similar to zomato or swiggy) and so on depends on the user's desired quantity.

**Comment by shradiphylleia** [comment]
feature for increasing quantity or feature like amazon/flipkart frequently bought together section under that product.

**Comment by prathamkandari** [comment]
@shradiphylleia Feature of increasing the quantity

**Comment by shradiphylleia** [comment]
I wish to work on this issue.

**Comment by prathamkandari** [comment]
Ohkay

**Comment by prathamkandari** [comment]
Issue completed!
